### ISSUE TITLE
Instructions for creating a new twitter app

### ISSUE THREAD

**Issue by TimTruston** [chrismcband/tweet-search#3]
Great presentation and demo. Im trying to set this up on my machine...

1. Your instructions say create a new app on https://dev.twitter.com/ which is a maze for someone who just wants to create an app. Twitter apps are created on https://apps.twitter.com/ 
2. The form at apps.twitter.com asks for a website and callback url when creating an application. Would that be  http://localhost:3000 or  http://localhost:7890 ? kindly help.

**Comment by chrismcband** [comment]
Thanks for the suggestion of 1. I'll change that it to https://apps.twitter.com/

In my app on twitter I think I left the callback url blank. It's only needed if you're having to do a 3- legged oauth process, where you needed to fetch tweets from a different user. In this app it's only to get the command line twitter proxy to make requests for your account.

Here's a screenshot of my settings for the twitter app:
<img width="1053" alt="screen shot 2018-03-17 at 14 19 42" src="https://user-images.githubusercontent.com/196567/37556453-4f8ad97c-29ee-11e8-80e2-9003671b1b25.png">

**Comment by TimTruston** [comment]
Nevermind... I got it.
